- name: Do apt-get upgrade and reboot
  become: true
  hosts: "{{ target }}"
  tasks:
    - name: update
      command: apt-get upgrade -y

    - name: dist-upgrade
      command: apt-get dist-upgrade -y

    - name: autoremove
      command: apt-get autoremove -y

    - name: reboot
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true

    - name: wait for server up
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }}
