#!/bin/sh

if [ -z "$1" ]; then
	readlink inventory | sed -e 's/inventory\.//'
	exit
fi

case "$1" in
s|staging)
	name=staging
	;;
p|prod)
	name=prod
	;;
*)
	;;
esac

if [ -d inventory.$name ]; then
	rm -f inventory
	ln -sf inventory.$name  inventory
fi
