---
# tasks file for k8s-addon
- name: create manifest directory
  file: path=/root/manifest/addon state=directory

- name: copy manifests
  template: src=manifest/{{ item }}.yml dest=/root/manifest/addon/{{ item }}.yml
  with_items:
    - kubedns-deploy
    - kubedns-svc
    - nfs-pv
    - nfs-pvc

- name: apply manifests
  command: kubectl apply -f /root/manifest/addon/{{ item }}.yml
  with_items:
    - kubedns-deploy
    - kubedns-svc
    - nfs-pv
    - nfs-pvc
