apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ item.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ item.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: {{ item.subject.type }}
  name: {{ item.subject.name }}
