apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver
      --etcd-servers=http://127.0.0.1:2379
      --etcd-servers-overrides=/events#http://127.0.0.1:4002 
      --service-cluster-ip-range={{ k8s_svc_cluster_ip_range }}
      --insecure-bind-address=0.0.0.0
      --v=0
      --allow-privileged=True
      1>>/var/log/kube-apiserver.log 2>&1
    image: gcr.io/google_containers/kube-apiserver:{{ k8s_ver }}
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: local
      protocol: TCP
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /var/log/kube-apiserver.log
      name: logfile
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/log/kube-apiserver.log
    name: logfile
