---
# tasks file for k8s-common
- name: create directories
  file: name={{ item }} state=directory
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/manifests

- name: install docker
  apt: name=docker.io
  notify: restart docker

- name: install docker unit file
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/systemd/system/docker.service
  notify: restart docker

- name: install docker environment file
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/kubernetes/docker
  notify: restart docker

# k8s common
- name: copy k8s binary
  copy:
    src: "{{ k8s_get_dir }}/kubernetes/server/bin/{{ item }}"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
    remote_src: True
  with_items:
    - kubelet
    - kube-proxy
  notify:
    - restart kubelet
    - restart kube-proxy

- name: install common config file
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/kubernetes/config
  notify:
    - restart kubelet
    - restart kube-proxy

# kubelet
- name: create directories
  file: name={{ item }} state=directory mode=0750
  with_items:
    - /var/lib/kubelet

- name: install kubelet unit file
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/systemd/system/kubelet.service
  notify: restart kubelet

- name: install kubelet environment file
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/kubernetes/kubelet
  notify: restart kubelet

# kube-proxy
- name: create log files
  file: name={{ item }} state=touch
  with_items:
    - /var/log/kube-proxy.log

- name: install kube-proxy unit file
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/systemd/system/kube-proxy.service
  notify: restart kube-proxy

- name: install kube-proxy environment file
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/kubernetes/proxy
  notify: restart kube-proxy

#- name: copy manifests
#  template: src={{ item }} dest=/{{ item }}
#  with_items:
#    - etc/kubernetes/manifests/kube-proxy.yaml
